Fix issues #39 and #40
wright-group/bluesky-cmds pull request #41
Opened 2022-08-12 20:58 UTC by pcruzparri

2022-08-15 04:44 UTC, ksunden commented on bluesky_cmds/somatic/plan_ui.py
> +                self.device.associate(value[self.name]["device"])
where did you get `associate` from???

It is literally not used in this codebase anymore...

2022-08-15 05:17 UTC, ksunden commented
I noticed something else wrong while testing this, just went and fixed it.

2022-08-15 05:18 UTC, ksunden commented on bluesky_cmds/somatic/plan_ui.py
> +                self.device.associate(value[self.name]["device"])
It is still just "write"

2022-08-15 05:20 UTC, ksunden commented
General comment: I greatly recommend using informative and distinct commit messages rather than just doing the same generic "fixes for X" commit messages.

2022-08-15 05:20 UTC, ksunden requested changes
See inline comments

2022-08-15 05:23 UTC, ksunden commented
Additionally, I try _not_ to commit from the lab machines where it can be avoided... Highly recommend getting your own dev machine set up to be able to work out this kind of issue, where it is not reliant on the actual hardware to replicate.

2022-08-22 17:13 UTC, pcruzparri commented on bluesky_cmds/somatic/plan_ui.py
> +        if "motor" in value:
Sorry, but I'm not sure what the first comment means. Are you saying it should be just calling the read() method of self.center, self.width, and self.npts?

2022-08-22 17:30 UTC, ksunden commented on bluesky_cmds/somatic/plan_ui.py
> +        if "motor" in value:
there should not be this `if` statement

that entry does not exist in the kwargs

2022-08-22 17:35 UTC, ksunden commented on bluesky_cmds/somatic/plan_ui.py
> +        if "motor" in value:
it should reflect the `kwargs` getter, that returns a flat dictionary with keys "method" (which there is only one option for at the moment, so there is no UI element for it, so that one can be ignored), "center", "width", and "npts".

So the setter should set the appropriate UI element for each of those keys.

But there is no mention of "motor" there

2022-08-26 16:26 UTC, ksunden approved these changes

2022-08-26 16:26 UTC, merged